/** See docs/data-model.md section 1. */
export type NodeType = 'textPrompt' | 'generateImage' | 'generate3d';

export type NodeStatus = 'idle' | 'pending' | 'ready' | 'error';

interface NodeBase {
  id: string;
  position: { x: number; y: number };
}

/** Start node — no input port, its `prompt` value is the output. */
export interface TextPromptNode extends NodeBase {
  type: 'textPrompt';
  prompt: string;
}

/**
 * Owner of an in-flight run. Only that client can finish the run, so peers use this to
 * tell a live `pending` from one abandoned by a disconnected client (docs/data-model.md 1).
 */
export interface NodeRunState {
  /** Yjs clientID of the client that started the run (same id as `AwarenessState.clientId`). */
  clientId: number;
  /** Epoch milliseconds when the run started. */
  startedAt: number;
}

/**
 * Input text is not stored here — it's resolved at execution time from the
 * connected TextPromptNode(s) via edges, to avoid duplicating that state.
 */
export interface GenerateImageNode extends NodeBase {
  type: 'generateImage';
  status: NodeStatus;
  imageUrl: string | null;
  errorMessage: string | null;
  /** Non-null only while `status` is `"pending"`. */
  pendingRun: NodeRunState | null;
}

/** Terminal node — no output port. `modelUrl` is the 3D asset generated by Meshy AI. */
export interface Generate3dNode extends NodeBase {
  type: 'generate3d';
  status: NodeStatus;
  modelUrl: string | null;
  errorMessage: string | null;
  /** Non-null only while `status` is `"pending"`. */
  pendingRun: NodeRunState | null;
}

export type PipelineNode = TextPromptNode | GenerateImageNode | Generate3dNode;
